version: '3'

services:
  backend:
    build: ./
    container_name: pet_project
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://neondb_owner:npg_XyuFp8LEQc1A@ep-sweet-bird-a5ipjx5t-pooler.us-east-2.aws.neon.tech/myDB?sslmode=require
      - CLIENT_URL=http://ec2-54-174-47-150.compute-1.amazonaws.com:3000

      - GOOGLE_CLIENT_ID=369842540444-qhs7fffk0rlmeoa35mdjcvntpjcl9atg.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=http://localhost:3000/auth/google/callback

      - FACEBOOK_CLIENT_ID=2193697871065462
      - FACEBOOK_CLIENT_SECRET=c6756123ce6e9edd53bf981cda4d2cfe
      - FACEBOOK_CALLBACK_URL=http://localhost:3000/auth/facebook/callback

      - REFRESH_JWT_SECRET=b7XAI832pnCOVeW5tGxYkFSh0Zsvwiyz1DH4RqBfTKg6mcPluQ9oJMErULajdN
      - REFRESH_JWT_EXPIRE_IN=7d

      - JWT_SECRET=8ed4589c1eda66865eeb5d4c84084397f035dbc0aaa9cf930810620d05256cb3
      - JWT_EXPIRE_IN=1d

      - EMAIL_USER=juliakozyk999@gmail.com
      - EMAIL_PASS=gosy ptwt qgrj nepo

      - REDIRECT_URL=http://localhost:5173

      - TWILIO_ACCOUNT_SID=ACf1a525a6f7f5670eaae4027d4a78a6df
      - TWILIO_AUTH_TOKEN=5ac357ab354118625d942a97541f09cc
      - TWILIO_FROM_NUMBER=+16315384146
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - nestjs_network

  database:
    image: postgres
    container_name: postgres_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nestjs_network

volumes:
  pgdata:

networks:
  nestjs_network:
    driver: bridge
